package presentacion;


import aplicacion.BudgetService;
import aplicacion.IBudgetRepository;
import dominio.Transaccion;
import infraestructura.persistence.MySQLBudgetRepository;
import infraestructura.ui.BudgetController;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aflor
 */
public class BudgetForm extends javax.swing.JFrame {
    private BudgetController controller;
    private BudgetService service;
    private IBudgetRepository repository;
    
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BudgetForm.class.getName());

    /**
     * Creates new form BudgetForm
     */
    public BudgetForm() {
        initComponents();
        repository = new MySQLBudgetRepository();
        service = new BudgetService(repository);
        controller = new BudgetController(service);
        tableModel = new DefaultTableModel(new Object[]{"Fecha","Tipo", "Descripción", "Monto"}, 0);
        tbl_movimientos.setModel(tableModel);
        actualizarVista();
    }
    
    private void actualizarVista() {
        
        // Limpiar tabla
        tableModel.setRowCount(0);
        
        // Obtener datos a través del controlador
        List<Transaccion> lista = controller.obtenerHistorial();
        for (Transaccion t : lista) {
            System.out.println(t.toString());
            tableModel.addRow(new Object[]{
                t.getFecha(), 
                t.getClass().getSimpleName(), 
                t.getDescripcion(), 
                t.getMonto()
            });
        }
        // Actualizar saldo con lógica de dominio
        /*Double saldo = controller.obtenerSaldoActual();
        lblSaldo.setText("Saldo Actual: $" + String.format("%.2f", saldo));
        lblSaldo.setForeground(saldo >= 0 ? Color.BLUE : Color.RED);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_movimientos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_movimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_movimientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BudgetForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_movimientos;
    // End of variables declaration//GEN-END:variables
}
